### ISSUE TITLE
Integrate adminer-custom into the project

### ISSUE THREAD

**Issue by justinhartman** [justinhartman/lamp-ssl#6]
## Todo

* [x] Integrate `adminer-custom` to project.
* [x] Remove symbolic link.
* [x] Update `adminer-plugins` before integrating `adminer-custom` as the plugins need to come from that repo.

## Overview

Integrate [@justinhartman/adminer-custom](https://github.com/justinhartman/adminer-custom) into the project for version-1.0.0.

### version-0.1.2

Symbolic link to `/adminer/` has been added in version-0.1.2. This will be replaced by [@justinhartman/adminer-custom](https://github.com/justinhartman/adminer-custom) when I'm done with that particular project. For now the reference (symlink) is needed.

There is actually also a dependency on [@justinhartman/adminer-plugins](https://github.com/justinhartman/adminer-plugins) as I need that project:

1. Updated to the latest version
2. Code commenting to be applied

**Comment by justinhartman** [comment]
Symbolic link to `/adminer/` has been added in version-0.1.2. This will be replaced by [@justinhartman/adminer-custom](https://github.com/justinhartman/adminer-custom) when I'm done with that particular project. For now the reference (symlink) is needed.
